Rework INSTALL_CMD to touch/echo >&2 only as needed
Analogous to previous commit.

With this commit we no longer get the following erroneous messages
during `make distcheck'.

"
failed to copy INSTALL from util-macros: installing possibly empty INSTALL.
...
failed to copy INSTALL from util-macros: installing possibly empty INSTALL.
"

Cc: Gaetan Nadon <memsize@videotron.ca>
Cc: Peter Hutterer <peter.hutterer@who-t.net>
Signed-off-by: Emil Velikov <emil.velikov@collabora.com>
Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>

diff --git a/xorg-macros.m4.in b/xorg-macros.m4.in
--- a/xorg-macros.m4.in
+++ b/xorg-macros.m4.in
@@ -1839,7 +1839,8 @@ AC_REQUIRE([PKG_PROG_PKG_CONFIG])
 macros_datadir=`$PKG_CONFIG --print-errors --variable=pkgdatadir xorg-macros`
 INSTALL_CMD="(cp -f "$macros_datadir/INSTALL" \$(top_srcdir)/.INSTALL.tmp && \
 mv \$(top_srcdir)/.INSTALL.tmp \$(top_srcdir)/INSTALL) \
-|| (rm -f \$(top_srcdir)/.INSTALL.tmp; touch \$(top_srcdir)/INSTALL; \
-echo 'util-macros \"pkgdatadir\" from xorg-macros.pc not found: installing possibly empty INSTALL.' >&2)"
+|| (rm -f \$(top_srcdir)/.INSTALL.tmp; test -e \$(top_srcdir)/INSTALL || ( \
+touch \$(top_srcdir)/INSTALL; \
+echo 'failed to copy INSTALL from util-macros: installing empty INSTALL.' >&2))"
 AC_SUBST([INSTALL_CMD])
 ]) # XORG_INSTALL
